pipeline {
    agent {
        docker {
            image 'node:7-alpine'
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install'
                sh 'docker stop flask'
                sh 'docker swarm leave -f'
                sh 'docker build -t macalahthomas/tcmg476 .'
                sh 'docker swarm init'
                sh 'docker stack deploy -c docker-compose.yml flask'
            }
        }
        stage('Test'){
            agent{
                docker{
                    image 'python:3-alpine'
                }
            }
            steps{
                sh 'python3 -m pip install requests'
                sh 'python3 ./test.py'
                sh 'python3 ./commandlinetest.py'
            }
        }
        stage('Deploy'){
            steps{
                sh 'docker login -u macalahthomas -p Krev@pple1'
                sh 'docker push macalahthomas/tcmg476'
            }
        }
    }
}
